services:
  # Test runner for unit tests only
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: kurin-test-runner
    restart: "no"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TEST_ENVIRONMENT=true
      - LOG_LEVEL=DEBUG
      # Mock environment variables for tests
      - BOT_TOKEN=test_bot_token
      - ADMIN_IDS=12345,67890
      - GOOGLE_SHEETS_URL=https://docs.google.com/spreadsheets/d/test
      - GOOGLE_SHEET_NAME=TestBooks
      - ALLOWED_TIME_TO_READ_THE_BOOK=14
      - RULES_TEXT=Test rules for books
    volumes:
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    command: ["python", "tests/run_tests.py", "--unit"]
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 